name: Python-Script-run
on:
  push:
  workflow_dispatch:
    inputs:
      info:
        description: "Just print"
        required: true
        default: "Python"
        type: string
jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out code"
      uses: actions/checkout@v3
    - name: "Print Python Version"
      run: python --version
    - name: "Print Hello World via Python Script"
      run: python -c "print('India is my country')"
    
    - name: "Print current path"
      run: |
        hostname
        ifconfig -a
        pwd
        df -hT
